### ISSUE TITLE
[Credentials] credentials and groups

### ISSUE THREAD

**Issue by pjam** [symfony2admingenerator/GeneratorBundle#154]
Hi.

Could you give some pointers on how to use credentials in generator.yml?

I want a list field visible only with some credentials and tried
```yaml
fields:
    fieldname:
        credentials: [ROLE_SUPER_ADMIN]
```

without luck, error thrown "Could not set option "credentials" on "fieldname" column in "Entity" list builder.". Is it possible to use credentials for fields? How?

Regards

**Comment by tobias-93** [comment]
@pjam you need to utilize the groups functionality.
First you need to define the right `getGroups(Object $object)` function in the `EditController` and  `NewController` in which you assign groups with a certain name to the people with the right credentials like:
```php
 /**
   * Get groups.
   *
   * @param Object $Object
   * @return array
   */
  protected function getGroups(Object $Object)
  {
    return $this->get('security.authorization_checker')->isGranted("ROLE_SUPER_ADMIN") ? array(0 -> 'SUPER_ADMIN') : array();	
  }
```

Then you need to attach the credentials to the field in the generator.yml like:
```yaml
fields:
  fieldname:
    groups: [SUPER_ADMIN]
```
