### ISSUE TITLE
[Credentials] Templates don't display fields if one requires a group that current user doesn't match

### ISSUE THREAD

**Issue by sescandell** [symfony2admingenerator/GeneratorBundle#167]
I just faced a limitation to how we manage credentials in templates.

If I want to make one field available only if you have a given group, I'll do this:
```yaml
generator: admingenerator.generator.doctrine
params:
    model:              Admingenerator\DoctrineOrmDemoBundle\Entity\Post
    namespace_prefix:   Admingenerator
    i18n_catalog:       AdmingeneratorOrmDemoBundle
    concurrency_lock:   ~
    bundle_name:        DoctrineOrmDemoBundle
    pk_requirement: ~
    fields:
        author:
            filterable: 1
            groups: [non]
            filtersGroups: [oui]
```

Except that, because of this, fields in the same fieldset of this "protected" field are not anymore displayed in views if you don't have the group of the one particular protected field.
This is because templates contain the following code:

```twig
{% set fieldsetColumns = builder.columnsFor(fieldset) %}
            {% set fieldsetGroups = fieldsetColumns|mapBy('groups')|flatten %}

            {% if fieldsetGroups is not empty %}
                {{ echo_set('fieldsetGroups', echo_twig_arr(fieldsetGroups), false) }}
                {{ echo_if('fieldsetGroups|intersect(groups) is not empty') }}
            {% endif %}
```

Meaning that, if one field in your set of fields requires a group and the current user doesn't have it, all the fieldset is not displayed.

Issue is not so for linked to groups, but more to how tests on fieldsets are performed.

A simple way to see this in action is to define a group property on a field and let the `display: ~` configuration in any builder: no field is so displayed.
