### ISSUE TITLE
[Propel] Scopes list filter don't work

### ISSUE THREAD

**Issue by Lionel09** [symfony2admingenerator/GeneratorBundle#179]
The filter setted in the list builder for the different scope is not used: no error, but no filter either.

```
builders:
    list:
        params:
            title:                             Acme list
            max_per_page:           50
            sort:                            [ created_at, DESC ]
            scopes:
                group_1: 
                    "All":                     ~
                    "Foo":
                        default:                true
                        filters:
                            filterByPublished:  true
                    "Bar":
                        filters:
                            filterByPublished:  false
```

The "Foo" scope is displayed as expected (as the default one), but the "filterByPublished" is not called: every scope has the same result.

**Comment by bobvandevijver** [comment]
There are currently no developers active which use Propel in one of their projects. Maybe you can try to create a PR to fix this problem?

**Comment by Lionel09** [comment]
The propel config has evolved since generator v1 and now this config works fine:
```
builders:
    list:
        params:
            title:                             Acme list
            max_per_page:           50
            sort:                            [ created_at, DESC ]
            scopes:
                group_1: 
                    "All":                     ~
                    "Foo":
                        default:                1
                        filters:
                            published:  1             # instead of filterByPublished
                    "Bar":
                        filters:
                            published:  0             # instead of filterByPublished
            filters:    [ published ]
```

The "filters" array field have to contain the scope filter if we want the scope to work so I don't know if it works as expected. From what I've seen in the source, the ```getScopeFilters``` fills an array which is used in the ```processFilters```, but the ```processScopes``` function doesn't seem to do anything in that case.

**Comment by sescandell** [comment]
Hi @Lionel09 

You're right, in that specific case, `processScopes` doesn't do a lot. But it does one thing: activate default scope if any.

And, if you use scopes as follow, it allows you to customize filters thanks to new method:

```yml
        scopes:
                "First Group":
                    "Sample":
                        default: true
                        filters:
                            - myCustomAuthorFilter
                "Second group":
                    "Published":
                        default: true
                        filters:
                            "isPublished": 1
```

With this sample, in your controller you will have a method called `scopeMyCustomAuthorFilter($queryFilter);` that you can customize.
