### ISSUE TITLE
Filtrers

### ISSUE THREAD

**Issue by enkaho** [symfony2admingenerator/GeneratorBundle#198]
Hi, 

I can't display filters on List.
my xxx-generator.yml :
```
builders:
    list:
        params:
            title: List for TestBundle
            display: [ mail, username, enabled ]
            filters:    
                display: [ mail ]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
``` 
composer.json :
```
"symfony2admingenerator/generator-bundle": "^2.0@beta",
 "symfony/symfony": "^2.7",
```

**Comment by tobias-93** [comment]
Hi, you should not put the array with wanted filters under `display:` but directly under `filters:`

Regards, Tobias

**Comment by sescandell** [comment]
What @tobias-93 said is your generator should looks like this:

```yml
builders:
    list:
        params:
            title: List for TestBundle
            display: [ mail, username, enabled ]
            filters:  [ mail ]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
```

You probably also need to define your field as filterable in global section

**Comment by enkaho** [comment]
Hi, Thx for yours replies, but this is the same result with 

```
generator: admingenerator.generator.doctrine
params:
    model: MyBundle\UserBundle\Entity\User
    namespace_prefix: MyBundle
    concurrency_lock: ~
    bundle_name: TestBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for TestBundle
            display: [ mail, username, enabled ]
            filters: [ mail ]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
``` 
In cache, Admingenerated/MyBundleTestBundle/Resources/views/UserList/filters.html.twig is empty...
And I don't understand why !

**Comment by ksn135** [comment]
Did you clear the cache ?

**Comment by enkaho** [comment]
yes

**Comment by bobvandevijver** [comment]
Is the email-field a simple text-field in your database?

**Comment by sescandell** [comment]
Did you defined your field as `filterable` in the `global` section of your generator.
Like this:

```yml
generator: admingenerator.generator.doctrine
params:
    model:              Admingenerator\DoctrineOrmDemoBundle\Entity\Post
    namespace_prefix:   Admingenerator
    i18n_catalog:       AdmingeneratorOrmDemoBundle
    concurrency_lock:   ~
    bundle_name:        DoctrineOrmDemoBundle
    pk_requirement: ~
    fields:
        author:
            filterable: 1
            # groups: [non]
            # filtersGroups: [oui]
        category:
            filterable: 1
            filterOn: category.name
        isPublished:
            filterable: 1
        expirationDate:
            filterable: 1
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
```
