### ISSUE TITLE
Problem with CKEditor pluged with generatorBundle and translation

### ISSUE THREAD

**Issue by rpostolov** [symfony2admingenerator/GeneratorBundle#214]
Hi everyone !

I'm using CKEditor with AdminGenerator (the new version 'GeneratorBundle') and translation. But the editor doesn't appear and i have an issues with the parameter 'config_name'.

Here is my configuration :

PageAdmin-generator.yml
```

      translations:
          label:              global.translations            
          formType:           a2lix_translations_gedmo
          addFormOptions:
              fields:
                  titreH1:                    
                      label:  Title H1
                  titreH2:                    
                      label:  Title H2
                  resume:                    
                      label:  Short description
                  contenu:                    
                      label:  content 
                      formType: ckeditor    
                      config_name: 'basic_img'
```

config.yml
```
ivory_ck_editor:
    configs:

        basic:
            toolbar:  basic  
        basic_img:
            toolbar:  basic_img              
        simple:
            toolbar:  simple 
            
    toolbars:
        configs:
            basic: [ [ "Source" , "-" , "Save" , "Undo" , "Redo",  "-" , "Bold" ,  "Italic" , "Underline" , "Strike" , "Subscript" , "Superscript" , "-" ,  "Format" , "NumberedList", "BulletedList", "-" , "Link" , "Unlink" , "Anchor" , "-" , "RemoveFormat" , "Maximize" ] ]
            basic_img: [ [ "Source" , "-" , "Save" , "Undo" , "Redo" , "-", "JustifyLeft" , "JustifyCenter" , "JustifyRight" , "JustifyBlock" , "-" , "Bold" ,  "Italic" , "Underline" , "Strike" , "Subscript" , "Superscript", JustifyLeft , "-" ,  "Format" , "NumberedList", "BulletedList", "-" , "Image" , "-" , "Link" , "Unlink" , "Anchor" , "-" , "RemoveFormat" , "Maximize" ] ]           
            simple: [ [ "Undo" , "Redo",  "-" , "Bold" ,  "Italic" , "Underline" , "Strike" ] ]                       
            demo: [ [ "Source" ], "/", [ "Anchor" ], "/", [ "Maximize" ] ]    
```

Can someone help me please ? I'm stuck with this problem 4 days...

Thanks a lot and have a nice day !

**Comment by bobvandevijver** [comment]
If the editor does not appear, check what is wrong in your browsers developers console: it will probably give a JavaScript error somewhere. 

Are you sure this problem is AdminGenerator related? As in, does it work when you create the form yourself in a controller?

**Comment by rpostolov** [comment]
Thanks for your answer. I have a problem with this configuration first. Like i said with this configuration i have an issue with config_name parameter it say :
```
The option "config_name" does not exist
```
But when i remove config_name i have an issue with formType, it's say : 

```
The option "formType" does not exist
```

I didn't found another example of configuration with admingenerato and translation. I want to know first how to configure CKEditor with them both. Because i'm not sure of my configuration right now.

If you have some example you'r welcome :)

**Comment by bobvandevijver** [comment]
Okay, now I know what your problem is. Try the following config:

```yaml
translations:
    label:              global.translations            
    formType:           a2lix_translations_gedmo
    addFormOptions:
        fields:
            titreH1:                    
                label:  Title H1
            titreH2:                    
                label:  Title H2
            resume:                    
                label:  Short description
            contenu:                    
                label:  content 
                field_type: ckeditor    
                form_options:
                    config_name: 'basic_img'
```

You will need to replace the `formType` under the `contenu` with `field_type`, as also given at http://a2lix.fr/bundles/translation-form/. Remember, when you already in a `addFormOptions` context, the complete value is given as array to the `a2lix_translations_gedmo` options (and merged with some default options). 
The same holds for the `config_name`: that will need to be in the `form_options` of the translation field (as also indicated in the a2lix documentation). 

This should do the trick and is indeed not an AdminGenerator problem.

**Comment by rpostolov** [comment]
Thanks for your help !

But there are a small error with this config, here is what i did :

```
translations:
          label:              global.translations            
          formType:           a2lix_translations_gedmo
          addFormOptions:
              fields:
                  titreH1:                    
                      label:  Title H1
                  titreH2:                    
                      label:  Title H2
                  resume:                    
                      label:  Short description
                  contenu:                    
                      label:  content 
                      field_type: ckeditor
                      config_name: 'basic_img'
                      
                  titreMenu:                    
                      label:  Menu title                              
                  titreSeo:                    
                      label:  SEO title
                  descriptionSeo:                    
                      label:  SEO description             
````

Thanks a lot now all it's ok !
