### ISSUE TITLE
How to / Filtering scope w. "more complex" query

### ISSUE THREAD

**Issue by Lionel09** [symfony2admingenerator/GeneratorBundle#232]
I'm trying to filtering my "scope" list result with more complex query than "column == value", is it possible?

Some examples of what I would like to do:
```
builders:
    list:
        params:
            title:                              List
            max_per_page:            50
            sort:                              [ published_at, DESC ]
            scopes:
                group_1: 
                    "Published":
                        default:                1
                        filters:
                            my_column:        [ 1, "<>"]   # my_column not equal to 1
                            myObjectMethod:    someValue  # can I use "virtual" field related to a value returned by current object?
                            query:              MyObjectQuery::create()->filterByColumn(...)  # custom Propel query? could try... :)
```                  
                         

What's the best actual strategy to reach my goal?
Thanks!

**Comment by calvera** [comment]
generator:

```yaml
            scopes:
                dates:
                    future:
                        default: true
                        icon: fa-plus-square
                        filters: [ future ]
                    all:
                        icon: fa-check-square
```

ListController:

```php
use Admingenerated\...\BaseBankHolidayController\ListController as BaseListController;

class ListController extends BaseListController {
	protected function scopeFuture($queryFilter) {
		$queryFilter->getQuery()->andWhere('q.holidayDate >= CURRENT_DATE()');
	}
}
