### ISSUE TITLE
How to / menu

### ISSUE THREAD

**Issue by Lionel09** [symfony2admingenerator/GeneratorBundle#239]
Recent lib update breaks something in menu construction: could you please explain the new way to override the main menu?

The [cookbook](https://github.com/symfony2admingenerator/GeneratorBundle/blob/master/Resources/doc/cookbook/menu.md) way gives me now:

```
Type error: Argument 1 passed to Admingenerator\GeneratorBundle\Menu\AdmingeneratorMenuBuilder::__construct() must implement interface Knp\Menu\FactoryInterface, none given, called in /var/www/myproject/vendor/knplabs/knp-menu-bundle/Provider/BuilderAliasProvider.php on line 121
```

Thanks

**Comment by Lionel09** [comment]
here is my way, hope it's the good one :)

custom base_admin.html.twig
```
            {% block sidebar_menu %}
                {{ knp_menu_render('admingen_mysidebar') }}
            {% endblock %}
```

services.yml
```
    admingen.menu.default_builder:
        class: AdminBundle\Menu\AdminMenu
        arguments:
            - @knp_menu.factory
            - @request_stack
            - AdminHomepage
        tags:
            - { name: knp_menu.menu_builder, method: sidebarMenu, alias: admingen_mysidebar }
```
