### ISSUE TITLE
Undefined index FiltersType

### ISSUE THREAD

**Issue by Lionel09** [symfony2admingenerator/GeneratorBundle#240]
Env: SF2.8 + Generator 2.0.1

Without update, the generated code for a model listing throws now an Exception on ```FiltersType```

```Notice: Undefined index: \AdminBundle\Form\Type\CmsContent\FiltersType```

The real index seems to be ```AdminBundle\Form\Type\CmsContent\FiltersType```

it's ok w. Generator v2.0.0-beta43

**Comment by sescandell** [comment]
Hi @Lionel09 

Is your AdminBundle a Bundle without any Vendor prefix or not?

**Comment by Lionel09** [comment]
yes, without any prefix - it's a new habit for me in this fresh new project
and I've got my model classes in ```Model``` namespace

generator.yml header
```
generator: admingenerator.generator.propel
params:
    model: Model\CmsContent
    namespace_prefix: 
    concurrency_lock: ~
    bundle_name: AdminBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
```

**Comment by sescandell** [comment]
I'll check this evening ad let you know,

**Comment by bobvandevijver** [comment]
Well, as far as I understand using a vendor is the Symfony convention for bundle naming. I do not see why we should support an extra, non-conventional option as that would probably add extra, unnecessary and error-prone checks. 

@Lionel09 Wouldn't it be an option for you to use use the vendor prefix?

**Comment by Lionel09** [comment]
It's a "best pratice" by Fab Pot himself to not use this convention: if you create a new SF2.8 project with the symfony installer, you've got an AppBundle just inside the src folder.

BTW, no problem for me if it's cause troubles with this bundle, I'll create a vendor

**Comment by sescandell** [comment]
@Lionel09 

I think this comes from the fact that Model has no vendro... I'll double check that point ASAP.

**Comment by Lionel09** [comment]
thanks @sescandell but I'll migrate to a vendor because I discover other little breaks as @bobvandevijver guess, for example #229

**Comment by sescandell** [comment]
OK.

But we are agree that this is because there is no vendor in the namespace of the Model right ? Not the bundle itself ?

**Comment by Lionel09** [comment]
No vendor for the bundle causes troubles like #229 but I cannot tell for this one

**Comment by Lionel09** [comment]
I've moved all my code to an "App" vendor name, and used the good old convention to generate my AdminBundle.

The generated code for list is now ok, but I've a similar problem in edit mode:

```Notice: Undefined index: \Symfony\Component\Form\Extension\Core\Type\IntegerType```

Real index is ```Symfony\Component\Form\Extension\Core\Type\IntegerType```

generator file:
```
generator: admingenerator.generator.propel
params:
    model: App\Model\CmsCategory
    namespace_prefix: App
    concurrency_lock: ~
    bundle_name: AdminBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
```
Notice that my model classes are not inside the AdminBundle.

Any idea?
