### ISSUE TITLE
Disable an option in a choice list

### ISSUE THREAD

**Issue by rpostolov** [symfony2admingenerator/GeneratorBundle#249]
Hi every body !

I would like to know how to disable an optiion in a choice list in a generator.yml file.

I have this in Admin-generator.yml :

```
fields:
      role:
        label: Role    
        formType: choice
        addFormOptions:
          choices:
            Administrator: Administrator
            Associate: Associate 
            Publisher: Publisher  
            Clerk: Clerk
            Blogger: Blogger  
```

And i want to disable the option 'Associate': Associate

The user can see this option but can't select it.

Thank's a lot !

Have a great day :)

**Comment by bobvandevijver** [comment]
You should try to add the correct FormOption just as you would do with a normal (non-admin) form (see this [StackOverflow](http://stackoverflow.com/questions/31535943/symfony-choice-type-with-disabled-options)). This would result in something like this:

```yaml
fields:
  role:
    addFormOptions:
      choice_attr: "function($key, $val, $index) { //Do something };"
```

However note that this is only a client-side check, and that user who can handle an inspector can still submit the disabled value. So, you should also use the controller to check if this option was selected such that you can reject it.
