### ISSUE TITLE
[Feature] multi-report excel builder

### ISSUE THREAD

**Issue by ksn135** [symfony2admingenerator/GeneratorBundle#262]
Sometimes you need to export same list in several different excel formats.
May be we should extend admin generator for such cases?
Proposed new featured "multi-report" excel builder format:
```yaml
builders:
    excel:
        params: 
            export:  # changed by @bobvandevijver proposal
               full:
                  credentials: 'hasRole("ROLE_ADMIN")'        
                  icon:   fa-files-o 
                  label:  Full report
                  filename: ~
                  filetype: ~
                  datetime_format: ~
                  fields: ~
                  display: 
                    - id
                    - guid
                    - dirty
                    - textState
                    - kind
                    - fullName
               short:
                  credentials: 'hasRole("ROLE_A")'        
                  icon:   fa-file-excel-o
                  label:  Short report
                  display: 
                    - id
                    - textState
                    - fullName
               simple:
                  credentials: 'hasRole("ROLE_B")'        
                  icon:   fa-table
                  label:  Simple report
                  fields:
                    fullName:
                      label:  List of items
                  display: 
                    - fullName
```
1) For each report new route auto-generated (<module>/excel/<key>)
2) Draw dropdown menu with all available reports for current user
3) Each report is independent and fully customisable 
Let's discuss it!
