### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by pjam** [symfony2admingenerator/GeneratorBundle#306]
Hi guys.

Anyone is using sort in the list builder? I tried to use it in one of my generator and got an exception.
It tries a query like select distinct id from (select ... from table) order by field. Of course, the order by outside the subselect is illegal, not in select list. 

Any workaround for this, or am I missing something?

I'm using the latest symfony version.

**Comment by sescandell** [comment]
Hi @pjam 

Could you show us you generator.yml file and/or your associated Controller?

Thanks,

**Comment by pjam** [comment]
Sure, here it is the generator:
```yaml
generator: admingenerator.generator.doctrine
params:
    model: AdminBundle\Entity\SlotVoucher
    namespace_prefix: 
    concurrency_lock: ~
    bundle_name: AdminBundle
    pk_requirement: ~
    fields: 
        numDisponiveis: 
            label: Vouchers Possíveis
            addFormOptions:
              attr:
                min: 1
        numUsados:
            label: Vouchers Imprimidos
            addFormOptions:
              attr:
                readonly: readonly
        dataAtribuicao:
            label: A partir de
            formType: Admingenerator\FormExtensionsBundle\Form\Type\DatePickerType
            dbType: date
            addFormOptions:
              attr:
                readonly: readonly
              config: 
                format: DD-MM-YYYY
        dataValidade:
            label: Válido até
            formType: Admingenerator\FormExtensionsBundle\Form\Type\DatePickerType
            dbType: date
            addFormOptions:
              attr:
                readonly: readonly
              config: 
                format: DD-MM-YYYY
        textoOrigem:
            label: Origem
        membro:
            formType: Admingenerator\FormExtensionsBundle\Form\Type\Select2EntityType
            formOptions:
                class: AdminBundle\Entity\Membro
                choice_label: nome
                placeholder: Escolher o membro...
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Lista de Vouchers Obtidos pelos Membros
            display: [membro, dataAtribuicao, numDisponiveis, textoOrigem, numUsados, dataValidade]
            sort: [ dataAtribuicao, 'DESC' ] 
            actions:
                new: 
                  label: Oferecer Vouchers
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: Oferecer Vouchers a um Membro
            display: [membro, numDisponiveis]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: Alterar Vouchers Disponíveis
            display: [membro, dataAtribuicao, numDisponiveis, numUsados, dataValidade]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: SlotVoucher.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
```

And here is the generated controller:
```php
<?php

namespace Admingenerated\AdminBundle\BaseSlotVoucherController;

use \AdminBundle\Form\Type\SlotVoucher\FiltersType;
    use Symfony\Component\Security\Core\Exception\AccessDeniedException;
    use Symfony\Component\Security\Core\Exception\InvalidCsrfTokenException;


use Admingenerator\GeneratorBundle\Controller\Doctrine\BaseController as BaseController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

use Pagerfanta\Pagerfanta;
use Pagerfanta\Adapter\DoctrineORMAdapter as PagerAdapter;

class ListController extends BaseController
{
    public function indexAction(Request $request)
    {
        $this->request = $request;
            

        $this->parseRequestForPager();

        // Scopes have to be processed before the filter form is initialized
        // so default scopes are synchronized with filters.
        $scopes = $this->getScopes();
        $form = $this->getFilterForm();

        return $this->render('AdminBundle:SlotVoucherList:index.html.twig', $this->getAdditionalRenderParameters() + array(
            'SlotVouchers' => $this->getPager(),
            'listRoute'                 => $this->getListRoute(),
            'filtersUrl'                => $this->getFiltersUrl(),
            'form'                      => $form->createView(),
            'sortColumn'                => $this->getSortColumn(),
            'sortOrder'                 => $this->getSortOrder(),
            'scopes'                    => $scopes,
            'perPageChoices'            => $this->getPerPageChoices(),
        ));
    }
    /**
     * Check if request contains pager parameters and
     * persist them in session if any.
     */
    protected function parseRequestForPager()
    {
        if ($this->request->query->get('page')) {
            $this->setPage($this->request->query->get('page'));
        }

        if ($this->request->query->get('perPage')) {
            $this->setPerPage($this->request->query->get('perPage'));
        }

        if ($this->request->query->get('sort')) {
            $this->setSort($this->request->query->get('sort'), $this->request->query->get('order_by','ASC'));
        }
    }

    /**
     * Store in the session service the current page
     *
     * @param integer $page The page number
     */
    protected function setPage($page)
    {
        $this->get('session')->set($this->getSessionPrefix().'List\Page', $page);
    }

    /**
     * Return the stored page
     *
     * @return integer $page The page number
     */
    protected function getPage()
    {
        return $this->get('session')->get($this->getSessionPrefix().'List\Page', 1);
    }

    /**
     * Return array of possible perPageChoices
     *
     * @return array
     */
    protected function getPerPageChoices()
    {
        return array(  0 => 10,  1 => 25,  2 => 50,  3 => 75,  4 => 100,);
    }

    /**
     * Store in the session service the perPage
     *
     * @param integer $perPage The perPage number
     */
    protected function setPerPage($perPage)
    {
        $this->get('session')->set($this->getSessionPrefix().'List\PerPage', $perPage);
    }

    /**
     * Return the stored perPage
     *
     * @return integer $perPage The perPage number
     */
    protected function getPerPage()
    {
        return $this->get('session')->get($this->getSessionPrefix().'List\PerPage', 10);
    }

    protected function getPager()
    {
        $paginator = new Pagerfanta(new PagerAdapter($this->getQuery()));
        $paginator->setMaxPerPage($this->getPerPage());
        $paginator->setCurrentPage($this->getPage(), false, true);

        return $paginator;
    }
    /**
     * Store in the session service the current sort
     *
     * @param string $column The column
     * @param string $order_by The order sorting (ASC,DESC)
     */
    protected function setSort($column, $order_by)
    {
        $this->get('session')->set($this->getSessionPrefix().'List\Sort', $column);

        if ($order_by == 'desc') {
            $this->get('session')->set($this->getSessionPrefix().'List\OrderBy', 'DESC');
        } else {
             $this->get('session')->set($this->getSessionPrefix().'List\OrderBy', 'ASC');
        }
    }

    /**
     * Return the stored sort
     *
     * @return string The column to sort
     */
    protected function getSortColumn()
    {
        return $this->get('session')->get($this->getSessionPrefix().'List\Sort', 'dataAtribuicao');
        }

    /**
     * Return the stored sort order
     *
     * @return string the order mode ASC|DESC
     */
    protected function getSortOrder()
    {
        return $this->get('session')->get($this->getSessionPrefix().'List\OrderBy', 'DESC');
        }


   /**
    * Action called on filter request. After the call, the user is redirected
    * to the list page.
    *
    * @param Request $request The request
    * @return RedirectResponse
    */
    public function filtersAction(Request $request)
    {
        $this->request = $request;
        if ($this->request->get('reset')) {
            $this->setFilters(array());
            // Remove scopes and re-apply default ones
            $this->setScopes(null);

            return $this->redirect($this->getListUrl());
        }

        if ('POST' === $this->request->getMethod()) {
            $form = $this->getFilterForm();
            $form->handleRequest($this->request);

            if ($form->isValid()) {
                $filters = $form->getViewData();
            }
        }

        if ('GET' === $this->request->getMethod()) {
            $filters = $this->request->query->all();

                    }

        if (isset($filters)) {
            // Set no active scope
            $this->setScopes(array());
            $this->setFilters($filters);
        }

        return $this->redirect($this->getListUrl());
    }

    /**
     * Store in the session service the current filters
     *
     * @param array the filters
     */
    protected function setFilters(array $filters)
    {$this->get('session')->set($this->getSessionPrefix().'List\Filters', $filters);
    }

    /**
     * Get filters from session
     */
    protected function getFilters()
    {
        $filters = $this->get('session')->get($this->getSessionPrefix().'List\Filters', array());return $filters;
    }

    protected function processFilters($queryFilter)
    {
        $filterObject = $this->getFilters();

        }

    
   /**
    * Returns the FilterType form FQCN
    *
    * @return string
    */
    protected function getFiltersType()
    {
        return 'AdminBundle\Form\Type\SlotVoucher\FiltersType';
    }

   /**
    * Get optional form filter options.
    *
    * @return array
    */
    protected function getFiltersOptions()
    {
        return array();
    }

   /**
    * Get list filters URL
    *
    * @return string
    */
    protected function getFiltersUrl()
    {
        return $this->generateUrl($this->getFiltersRoute());
    }

   /**
    * Get list filters route
    *
    * @return string
    */
    protected function getFiltersRoute()
    {
        return "AdminBundle_SlotVoucher_filters";
    }
    public function scopesAction(Request $request)
    {
        $this->request = $request;
        $this->setScope($this->request->get('group'), $this->request->get('scope'));

        return $this->redirect($this->getListUrl());
    }

    /**
     * Store in the session service the current scopes
     * If $scopes is null, simply remove any informations about scopes
     * (so in next request, defaults one will be used).
     *
     * @param null|array the scopes
     */
    protected function setScopes($scopes)
    {
        if (null === $scopes) {
            $this->get('session')->remove($this->getSessionPrefix().'List\Scopes');
        } else {
            $this->get('session')->set($this->getSessionPrefix().'List\Scopes', $scopes);
        }
    }

    /**
    * Change the value of one Scope
    *
    * @param string the group name
    * @param string the scope name
    */
    protected function setScope($groupName, $scopeName)
    {
        $scopes = $this->getScopes();
        $scopes[strtolower($groupName)] = strtolower($scopeName);
        $this->setScopes($scopes);

        $filters = array();
        foreach ($scopes as $scopeGroupName => $scopeName) {
            $filters += $this->getScopeFilters($scopeGroupName);
        }
        $this->setFilters($filters);

    }

    protected function getScopes()
    {
        if (null === $scopes = $this->get('session')->get($this->getSessionPrefix().'List\Scopes')) {
            $scopes = $this->getDefaultScopes();
            $this->setScopes($scopes);
            foreach ($scopes as $groupName => $scopeName) {
                $this->setScope($groupName, $scopeName);
            }
        }

        return $scopes;
    }

    protected function getDefaultScopes()
    {
        $scopes = array();

        
        return $scopes;
    }

    /*
    * @return string|null the scope setted for the current group
    */
    protected function getScope($groupName)
    {
        $groupName = strtolower($groupName);
        $scopes = $this->getScopes();

        return isset($scopes[$groupName]) ? $scopes[$groupName] : null ;
    }

    /**
     * @return array the filters for the $groupName scope
     */
    protected function getScopeFilters($groupName)
    {
        if (!$scope = $this->getScope($groupName)) {
            return array();
        }

        $groupName = strtolower($groupName);
        $filters = array();

        
        return $filters;
    }

    protected function processScopes($queryFilter)
    {
        }

        /**
    * Check user credentials
    *
    * @param string $credentials
    * @param \AdminBundle\Entity\SlotVoucher $SlotVoucher
    * @return boolean
    */
    protected function validateCredentials($credentials, \AdminBundle\Entity\SlotVoucher $SlotVoucher = null)
    {
    
    return $this->isGranted($credentials, $SlotVoucher);
    }

    /**
    * Throws exception if credentials are not validated
    *
    * @param string $credentials
    * @param \AdminBundle\Entity\SlotVoucher $SlotVoucher
    * @throws AccessDeniedException if is not allowed
    */
    protected function denyAccessUnlessValidateCredentials($credentials, \AdminBundle\Entity\SlotVoucher $SlotVoucher = null)
    {
    if (!$this->validateCredentials($credentials, $SlotVoucher)) {
    throw $this->createAccessDeniedException('Credentials unsatisfied');
    }
    }

    /**
     * Check crsf token provided for action
     *
     * @throw InvalidCsrfTokenException if token is invalid
     */
    protected function isGeneratedCsrfTokenValid($intention)
    {
        if (!$this->isCsrfTokenValid($intention, $this->request->request->get('_csrf_token'))) {
            throw new InvalidCsrfTokenException();
        }
    }



    /**
     * Get asession prefix
     *
     * @return string
     */
    protected function getSessionPrefix()
    {
        return '\AdminBundle\SlotVoucher';
    }

    /**
     * Get list index URL
     *
     * @return string
     */
    protected function getListUrl()
    {
        return $this->generateUrl($this->getListRoute());
    }

    /**
     * Get list index route
     *
     * @return string
     */
    protected function getListRoute()
    {
        return "AdminBundle_SlotVoucher_list";
    }

    /**
     * Get additional parameters for rendering.
     *
     * @return array
     */
    protected function getAdditionalRenderParameters()
    {
        return array();
    }

    /**
     * This function is for your convinience. Overwrite it if you need to
     * process the query.
     */
    protected function processQuery($query)
    {
        return $query;
    }

    protected function getQuery()
    {
        $query = $this->buildQuery();

        $this->processQuery($query);
        $this->processSort($query);

        $queryFilter = $this->getQueryFilter($query);
        $this->processScopes($queryFilter);
        $this->processFilters($queryFilter);

        return $query->getQuery();
    }

    protected function buildQuery()
    {
        return $this->getDoctrine()
                    ->getManagerForClass('AdminBundle\Entity\SlotVoucher')
                    ->getRepository('AdminBundle\Entity\SlotVoucher')
                    ->createQueryBuilder('q');
    }

    protected function processSort($query)
    {
        if ($this->getSortColumn()) {
            if (!strstr($this->getSortColumn(), '.')) { //direct column
                $query->orderBy('q.'.$this->getSortColumn(), $this->getSortOrder());
            } else {
                $finalColumn = $this->addJoinFor($this->getSortColumn(), $query, false);
                $query->orderBy($finalColumn, $this->getSortOrder());
            }
        }
    }

    protected function getFilterForm()
    {
        $filters = $this->getFilters();return $this->createForm(
            $this->getFiltersType(),
            $filters,
            $this->getFiltersOptions()
        );
    }

    protected function addJoinFor($table, $query, $currentObject = true)
    {
        if ($currentObject) {
            $query->leftJoin('q.'.$table, $table);
        } else {
            $tables = explode('.', $table);
            $previousTable = 'q';
            foreach (array_slice($tables, 0, -1) as $table) {
                $query->leftJoin(implode('.', array($previousTable, $table)), 'sort_' . $table);
                $previousTable = 'sort_' . $table;
            }
            return 'sort_' . $table . '.' . end($tables);
        }
        return null;
    }

        /**
     * @return \Admingenerator\GeneratorBundle\QueryFilter\QueryFilterInterface
     */
    protected function getQueryFilter($query)
    {
        $queryFilterClass = $this->container->getParameter('admingenerator.queryfilter.doctrine.class');

        return new $queryFilterClass($query);
    }

}
```

And finally, the thrown exception:
```
An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT DISTINCT id_0 FROM (SELECT s0_.id AS id_0, s0_.numDisponiveis AS numDisponiveis_1, s0_.dataAtribuicao AS dataAtribuicao_2, s0_.origem AS origem_3, s0_.numUsados AS numUsados_4, s0_.dataValidade AS dataValidade_5, s0_.created_by AS created_by_6, s0_.updated_by AS updated_by_7, s0_.deleted_by AS deleted_by_8 FROM slot_voucher s0_) dctrn_result ORDER BY dataAtribuicao_2 DESC LIMIT 10 OFFSET 0':

SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.dataAtribuicao_2' which is not in SELECT list; this is incompatible with DISTINCT") in Admingenerated/AdminBundle/Resources/views/SlotVoucherList/results.html.twig at line 110.
500 Internal Server Error - Twig_Error_Runtime
3 linked Exceptions: DriverException » PDOException » PDOException »
```
