### ISSUE TITLE
data range in filter - doctrine

### ISSUE THREAD

**Issue by snuffer82** [symfony2admingenerator/GeneratorBundle#324]
Hi!
I would like to add, in filters form, a start date and an end date (date range) based on a date field. How can I do?
I really appreciate your help
Paolo

**Comment by bobvandevijver** [comment]
You'll need to create your own filter action by overwriting the ListController of your admin generator. 

Below is an example of adding a two fields, which are then used to update the generated query for the list. You should be able to use this almost directly: add the two fields, and in their method (note that the names MUST match) you update the query accordingly. You do not have access to both field values at once when they are separate fields, but if your form value is the date range in object form, you can use it directly.

```yaml
# generator.yml (I've deleted all configuration which is not relevant for this answer)
generator: admingenerator.generator.doctrine
params:
  fields:
    registered:
      filterType: Symfony\Component\Form\Extension\Core\Type\ChoiceType
      addFilterOptions:
        required: true
        choices:
          Yes or No: NULL
          Yes: true
          No: false
        choices_as_values: true
    signedIn:
      filterType: Symfony\Component\Form\Extension\Core\Type\ChoiceType
      addFilterOptions:
        required: true
        choices:
          Yes or No: NULL
          Yes: true
          No: false
        choices_as_values: true
builders:
  list:
    params:
      filters: [ signedIn, registered ]
``` 

```php
// ListController.php
use Admingenerated\<YourBundle>\BaseAdminParticipationController\ListController as BaseListController;
use Admingenerator\GeneratorBundle\QueryFilter\DoctrineQueryFilter;
use Admingenerator\GeneratorBundle\QueryFilter\QueryFilterInterface;

/**
 * ListController
 */
class ListController extends BaseListController
{
  /**
   * @param QueryFilterInterface $queryFilter
   * @param                      $value
   */
  protected function filterSignedIn($queryFilter, $value)
  {
    assert($queryFilter instanceof DoctrineQueryFilter);
    if ($value !== NULL && $value) {
      $queryFilter->getQuery()->andWhere(sprintf('q.signout IS NULL'));
    } else {
      $queryFilter->getQuery()->andWhere(sprintf('q.signout IS NOT NULL'));
    }
  }

  /**
   * @param QueryFilterInterface $queryFilter
   * @param                      $value
   */
  protected function filterRegistered($queryFilter, $value)
  {
    assert($queryFilter instanceof DoctrineQueryFilter);
    if ($value !== NULL && $value) {
      $queryFilter->getQuery()->andWhere(sprintf('q.registered_at IS NOT NULL'));
      $queryFilter->getQuery()->andWhere(sprintf('q.registered_desk IS NOT NULL'));
    } else {
      $queryFilter->getQuery()->andWhere(sprintf('q.registered_at IS NULL'));
      $queryFilter->getQuery()->andWhere(sprintf('q.registered_desk IS NULL'));
    }
  }
}
```

You can always take a look into the generated files in your cache to see if it makes sense. Just look for the `Admingenerated` folder in your cache.

Hope this helps!
