### ISSUE TITLE
Filters on non displayed field is not possible

### ISSUE THREAD

**Issue by sescandell** [symfony2admingenerator/GeneratorBundle#62]
Adding a filter of a non displayed column is not possible via the generator.
Example of configuration not working:

``` yaml
generator: admingenerator.generator.doctrine
params:
    model:              Admingenerator\DoctrineOrmDemoBundle\Entity\Post
    namespace_prefix:   Admingenerator
    i18n_catalog:       AdmingeneratorOrmDemoBundle
    concurrency_lock:   ~
    bundle_name:        DoctrineOrmDemoBundle
    pk_requirement: ~
    fields:
        author:
            filterable: 1
        isPublished:
            filterable: 1
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: post.title.list
            display: [ id, author, title, tags ]
            filters:
                - author
                - isPublished
    ...
```

The `isPublished` filter is not displayed. To make it visible you have to add it in your list column (whereas it was not the case before).
