### ISSUE TITLE
Document column groups feature

### ISSUE THREAD

**Issue by loostro** [symfony2admingenerator/GeneratorBundle#9]

**Comment by bobvandevijver** [comment]
This one is not done yet... At least, not by me ;)

**Comment by sescandell** [comment]
What are we talking about by "Column groups"?

I thought it was about this kind of configuration:

```yaml
builders:
    edit:
        display:
            something:
                awesome: [field1, field2, field3]
```

Am I wrong? Or is it too late and I'm simply too tired to think about the right thing? :)

**Comment by bobvandevijver** [comment]
Actually, I have no clue... Maybe it's this?

```yaml
edit:
  params:
    display:
      "Name information":
        "row1 col-md-12": [ name ]
      "Gender information":
        "row2 col-md-12": [ gender ]
      "Address information":
        "row3 col-md-12": [ address ]
```

But that's also covered in the doc. @loostro, any light?
